# Generated by Django 2.2.4 on 2019-08-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_viewer', '0003_auto_20190829_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='category',
        ),
    ]
