# Generated by Django 2.2.4 on 2019-08-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_viewer', '0004_remove_bug_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
