# Generated by Django 2.2.4 on 2019-08-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viewer', '0006_auto_20190829_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(to='web_viewer.Tag'),
        ),
    ]
